import { createElement } from 'lwc';
import EventMainPage from 'c/eventMainPage';

describe('c-event-main-page', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-event-main-page', {
            is: EventMainPage
        });
        document.body.appendChild(element);
        expect(1).toBe(2);
    });
});